[package]
name = "bevy_sly_blender"
version = "0.1.0"
edition = "2021"


[features]
default = ["inspector", "registry"]
registry = [] # optional feature to enable the registry
inspector = [ "bevy-inspector-egui" ]
animation = [] # optional feature to enable the animation system

[dependencies]
bevy = { version = "0.13" }
ron = "0.8.1"
serde = "1.0.202"
serde_json = "1.0.117"
bevy-inspector-egui = { version = "0.24", optional = true }

[dev-dependencies]
bevy_asset_loader = { version = "0.20" }
